Error passing wrong version number to msvc linker
ENV: WinSDK8 VS2012 Compilation in 64 Bits
ERROR: error when linking client

CAUSE: msvc link support only major and minor version number. Before VS2012 extra number (like revision number) were stripped. Now the link throw an error with VS2012

see https://bugs.php.net/bug.php?id=63537 see http://msdn.microsoft.com/fr-fr/library/h88b7dc8(v=vs.110).aspx

--HG--
branch : StudioEtrange/error-passing-wrong-version-number-to-ms-1374694351376